### ISSUE TITLE
The yellow background

### ISSUE THREAD

**Issue by DutchPete** [mulfok/obsidian-absolve#1]
How do you get the yellow background. I tried the snippet in a default vault with no other snippets and no plug-ins, but the background stays white.

**Comment by mulfok** [comment]
Hey there! This is feature of kepano's Minimal theme. I like the colour scheme a lot, so I'll try to add it in today. If you could let me know what theme you're using, I'll try my best to make sure that my implementation works well with your theme!

**Comment by mulfok** [comment]
Okay! The option is there now~ Find it under "Aesthetics/Colours/Workspace/Light Workspace Colour Scheme"

Let me know if there are any issues, and I'll fix them up

https://github.com/mulfok/obsidian-absolve/releases/tag/v1.2.0-beta

**Comment by DutchPete** [comment]
Thanks for your quick reply. I apologize, but I found `Aesthetics`cannot find `/Colours/Workspace/Light Workspace Colour Scheme`. It could be that those long font codes are confusing me. Sorry.

Can you tell me which line number I have to scroll to?

BTW, I am using California Coast.

**Comment by mulfok** [comment]
Alright, no worries! First, make sure you have updated the snippet, and I'll let this screenshot explain a little better...
![image](https://user-images.githubusercontent.com/50339059/153456671-3482fbe9-795f-4996-8323-0cee74df601a.png)

Checking around with California Coast, there are more than a couple inconsistencies, so I'll work on getting those out!

**Comment by DutchPete** [comment]
Whoa, wait a minute! I was looking through the actual CSS code, yet your screenshot suggests it is a plug-in. So, how should I handle your CSS file?

**Comment by mulfok** [comment]
oh so sorry haha! I should specify that it is a snippet. Just stick absolve.css in `yourvault/.obsdian/snippets` and have the plugin Style Settings installed. Then open the open the command palette and find "Style Settings: Show style settings view"

**Comment by DutchPete** [comment]
No problem, the misunderstanding was mine: I thought Style Settings could only be used with plug-ins.

Anyway, it works, many thanks !

**Comment by DutchPete** [comment]
In the Absolve screenshot you show a slightly reddish shade at the top and bottom. Absolve does not seem to offer that option.

![image](https://user-images.githubusercontent.com/10794265/153467285-3b24a00a-13d6-4a09-9170-3500df31b0ac.png)

**Comment by mulfok** [comment]
yeah, the gradient is there just to make the whitespace around the screenshots a little more interesting—maybe it's possible to introduce this within the snippet, but as far as I know, I don't think that it is.

In other news, I've been going through the missing colour scheme elements in California Coast, and I should be ready to push it soon!

**Comment by DutchPete** [comment]
OK, thanks a lot for your help and indulgence with me. Don't worry about the shading, it is not important.

I like the concept of your snippet. I have a snippet pool from which I draw when I change theme, but that still requires a fair amount of time (although less so at each iteration, mind) to tweak it. Your snippet will nicely prevent some/a lot of that.

**Comment by DutchPete** [comment]
I thought a bit about it and can say my misunderstanding stems from calling it a snippet. So, after putting it in my snippet folder I enabled it, which mean everything was switched on.

It might be useful to not call it a snippet or else to make it clear how users should handle it.

**Comment by DutchPete** [comment]
Following on from my last comment, I realize I made a fool of myself: the snippet DOES need to be enabled for it to show up in the Style Settings.

So, please accept my sincere apologies, I will not bother you with this anymore 😊 
I will close this thread. Thanks again.
